- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  vars:
    contents: "{{ lookup('file', 'roles/common/vars/main.yml') }}"
  su: yes
  su_user: root
  roles:
    - common
